### ISSUE TITLE
Redline Crash Report

### ISSUE THREAD

**Issue by EXCLUSIVE19** [Pepnsi/BugReports#8]
[Window Title]
Error GTA5.exe!CPool::Release (0x4d)

[Main Instruction]
GTA5.exe!CPool::Release (0x4d)

[Content]
An error at GTA5.exe!CPool::Release (0x4d) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: minnesota-nine-october
Stack trace:
  GTA5.exe!CPool::Release (0x4d)
  GTA5.exe!sub_140ED11C4 (0x4b)
  GTA5.exe!sub_140ED29C0 (0x13)
  GTA5.exe!sub_140F0A578 (0x125)
  GTA5.exe!sub_1408FE350 (0x1b4)
  GTA5.exe!CScene::PreSceneUpdate (0x30)
  gta-core-five.dll!rage::RunEntries (0x1a1) (GameSkeleton.cpp:187)

[^] Hide details  [Save information] [Close]

[Expanded Information]
Crash signature: fivem.exe+1562171
Report ID: si-21e47a07a44a46c7b6bc861d43d61b4b
You can press Ctrl-C to copy this message and paste it elsewhere.

**Comment by Pepnsi** [comment]
Clear your cache.
